preset: recommended

risky: false
linting: true

disabled:
  - cast_spaces
  - heredoc_to_nowdoc
  - no_alias_functions
  - no_tab_indentation
  - phpdoc_var_without_name
  - single_import_per_statement
  - unalign_equals
  - unary_operator_spaces

enabled:
  - align_equals
  - blank_line_before_return
  - combine_consecutive_unsets
  - no_empty_comment
  - no_php4_constructor
  - no_useless_else
  - not_operator_with_successor_space
  - phpdoc_no_empty_return
  - phpdoc_property
