language: php

php:
  - 7

global:
  - CI=true
  - CI_ENV=testing

env:
  - DB=mysqli
  - DB=postgres

services:
  - mysql
  - postgresql

script:
  - php vendor/bin/phpunit -v

before_script:
  - composer install --prefer-source
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database IF NOT EXISTS test;'; fi"

