language: php

php:
  - 7

env:
  - DB_GROUP=mysql
  - DB_GROUP=postgre

script:
  - php phpunit.phar -v

services:
  - mysql
  - postgresql

before_install:
  - if [ $DB = 'mysql' ]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi
  - if [ $DB = 'postgre' ]; then psql -c 'create database test;' -U postgres; fi
