language: php

php:
  - 7

env:
  - DB=mysql
  - DB=postgre

script:
  - php phpunit.phar -v -c tests/travis/$DB.travis.xml

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
